server:
  port: 8084
  servlet:
    context-path: '/learn-purchase/'


spring:
  application:
    name: purchase-service
  datasource:
    url: jdbc:postgresql://localhost:5435/purchase
    username: joel
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true

logging:
  level:
    com.joel: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

