server:
  port: 8084
  servlet:
    context-path: '/learn-purchase/'


spring:
  application:
    name: learn-purchase-service
  datasource:
    url: jdbc:postgresql://localhost:5435/purchase
    username: joel
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.joel: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

learn:
  serviceRegistry:
    username: ${NAME}
    password: ${PASSWORD}
  auth:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 14400000
  broker:
    exchange:
      purchaseCommandExchange: learn.purchaseCommand
    queue:
      purchaseCommandQueue:
        name: learn.purchaseCommand.ms.purchase
    key:
      purchaseCommandKey: ms.purchase

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${learn.serviceRegistry.username}:${learn.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

